### ISSUE TITLE
SFOS 3.3.0

### ISSUE THREAD

**Issue by sailorhub77** [wdehoog/sailfish-bacon-images#14]
May I request an update to SFOS version 3.3.0, please?
At least according to many forum posts, it's going to contain a lot of useful features (flatpak etc.). I'd be very grateful for this!

**Comment by wdehoog** [comment]
Sorry but I stopped working on this.

**Comment by sailorhub77** [comment]
Oh my God, this news really hit me hard. For me, your port has been the best smartphone experience ever. I even bought a second OnePlus One for my dad.
Is there any way to maybe motivate you to look in this again? That would mean so much to me!

**Comment by wdehoog** [comment]
Well updating SailfishOS is a very frustrating experience for me. Lots' of stuff needs to be checked and fixed. As I do this on my own the fun has gone. I also am not using it anymore on my phone so not much incentive to continue.

But due to lockdown I have time so I will see if I can get 3.3 working without too much hassle.

**Comment by wdehoog** [comment]
Here is a first build. I would appreciate it if you give it a try: https://drive.google.com/open?id=1yCqzTlx76fuJmkJM2S2JY6AQ0UTgbkST

Camera is not working yet.

**Comment by sailorhub77** [comment]
You are the best!!! Thanks a million for all your help! I am sorry to hear this tends to be a frustrating experience. But trust me, your efforts are well appreciated!

I upgraded last night and as far as I can tell everything is working like a charm! Great work indeed!!!

BTW, I couldn't find a way to contact you directly here on Github. So, I left a message on maemo.org.
